# Generated by Django 5.0 on 2024-10-16 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("difficulties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="difficulty",
            name="score",
            field=models.FloatField(
                default=0,
                help_text="The score of the difficulty level.",
                validators=[django.core.validators.MaxValueValidator(1000)],
                verbose_name="Score",
            ),
            preserve_default=False,
        ),
    ]
