# Generated by Django 5.0 on 2024-09-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("difficulties", "0004_alter_difficulty_xp_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="difficulty",
            name="xp_penalty",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The amount of XP deducted when a challenge of this difficulty is failed.",
                verbose_name="XP Penalty",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="difficulty",
            name="xp_value",
            field=models.PositiveIntegerField(
                help_text="Number of xp value associated with this difficulty level.",
                verbose_name="XP Value",
            ),
        ),
    ]
