# Generated by Django 5.0 on 2024-10-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_alter_challenge_repeat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="ignore_for_ai",
            field=models.BooleanField(
                default=False,
                help_text="Exclude this challenge from AI suggestionsand difficulty predictions.",
                verbose_name="Ignore For AI",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="title",
            field=models.CharField(
                help_text="Title of the challenge.",
                max_length=80,
                verbose_name="Title",
            ),
        ),
    ]
