# Generated by Django 5.0 on 2024-09-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                default="M",
                help_text="Gender of the user",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
    ]
