# Generated by Django 5.0 on 2024-10-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usermodel_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                help_text="Gender of the user",
                max_length=6,
                verbose_name="Gender",
            ),
        ),
    ]
